number_list=["1","2","3","345","5","6","7","8","9","134","11","12","63","14",]
#print(number_list[0])
#print(number_list[1])
#print(number_list[2])
#print(number_list[3])
#print(number_list[4])
#print(number_list[5])
#print(number_list[6])
#print(number_list[7])
#print(number_list[8])
#print(number_list[9])
#print(number_list[10])
#print(number_list[11])
#print(number_list[12])
#print(number_list[13])
for i in range (20):
    print(number_list[i])
